[package]
name = "database"
version = "0.0.1"
edition = "2024"
authors = ["markhenry.liwag@gmail.com"]

[dependencies]
async-once-cell = "0.5.4"
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio"] }